language: rust

notifications:
  email:
    on_success: never
    on_failure: always

sudo: required

install:
  - sudo apt-get install nasm qemu-system
  - ./downloadrustlibdir.sh
script:
  - make
  - "{ sleep 10; echo q; } | qemu-system-i386 -kernel bin/kernel.bin -monitor stdio -display none"
