language: rust

env:
  - ARCH=x86
  - ARCH=x86_64

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - sudo apt-get update -qq
  - sudo apt-get install nasm qemu-system
  - make download 
script:
  - make
  - "{ sleep 10; echo q; } | qemu-system-i386 -kernel bin/kernel.elf -monitor stdio -display none"
